### ISSUE TITLE
About training consumption and inference speed

### ISSUE THREAD

**Issue by silence-tang** [theEricMa/OTAvatar#23]
Great work, it inspired me a lot!

May I ask the GPU memory needed to train the model? I don't have many GPUs and I'm afraid that the experiment can't be reproduced normally.

Besides, I'm also curious about the inference time (FPS). 

Looking forward to hearing from you, thanks!

**Comment by theEricMa** [comment]
Thank you for your interest in our research on 3D talking faces. We recognize there are many concurrent efforts focused on creating generalizable and one-shot 3D talking face models. However, our approach stands out in its efficiency, requiring less GPU usage than other methods. Rather than training a model from scratch, we build on top of a pre-trained 3D GAN to achieve controllable facial motion. Specific details on the GPU requirements and inference times of our method can be found in our paper and demo video, respectively.
