### ISSUE TITLE
metric code about cross-identity reenactment

### ISSUE THREAD

**Issue by Harold0530-zhang** [theEricMa/OTAvatar#27]
@theEricMa Could you share the codes about FID、AKD、AED、CSIM、APD？I check repos like PIRenderer、FOMM and StyleHeat, but only FOMM share the code about AED and AKD, which maybe right. So we wish you sincerely release your codes about criteria on cross-identity reenactment.

**Comment by theEricMa** [comment]
Hi, thank you for your interest in our code.

- The CSIM is exactly the same as the identity loss in our [code](https://github.com/theEricMa/OTAvatar/blob/3944c2ed45ba86b084905614f82909538c48ef7c/loss/identity.py#L354) which calculates the cosine similarity on the identity embedding extracted from the aligned gt and pred portraits.

- The AKD is the L1 similarity between the 68 facial keypoints extracted from the gt and pred portraits using [face_alignment](https://github.com/1adrianb/face-alignment) tools.

- The APD and AED are the L1 similarity between the pose and expression coefficients extracted from gt and pred portraints using[ DeepFaceRecon](https://github.com/microsoft/Deep3DFaceReconstruction).  We use the original [weight](https://drive.google.com/drive/folders/1liaIxn9smpudjjqMaWWRpP0mXRW_qRPP?usp=sharing), instead of their update in 2023.4. Specifically, the expression coefficients are 64 digits from [here](https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/b9e6fa89ea1566bb9ec27922f6f5d87c34b4b261/models/bfm.py#L261), and the pose coefficients are the concatenation of [rotation](https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/b9e6fa89ea1566bb9ec27922f6f5d87c34b4b261/models/bfm.py#L263) and [translation](https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/b9e6fa89ea1566bb9ec27922f6f5d87c34b4b261/models/bfm.py#L265).

For any further questions, please feel free to contact me.
